# Generated by Django 5.0.3 on 2024-03-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
