# Generated by Django 5.0.3 on 2024-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_user_is_dealer_alter_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_dealer',
            field=models.BooleanField(default=False, verbose_name='Is dealer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is user'),
        ),
    ]
